version: '3'
services:
  db:
    image: yashoza19/mysql:latest
    environment:
      MYSQL_DATABASE: 'employees'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  # Names our volume

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000 --noreload
    ports:
      - "8000:8000"
    volumes:
      - .:/my_app_dir
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - db

volumes:
  my-db: